"""Prompt templates for VulTrial agents"""

from .agent_prompts import (
    # Main prompts
    SECURITY_RESEARCHER_PROMPT,
    CODE_AUTHOR_PROMPT,
    MODERATOR_PROMPT,
    REVIEW_BOARD_PROMPT,
    # Later turn prompts
    SECURITY_RESEARCHER_PROMPT_LATER,
    CODE_AUTHOR_PROMPT_LATER,
    MODERATOR_PROMPT_LATER,
)

__all__ = [
    'SECURITY_RESEARCHER_PROMPT',
    'CODE_AUTHOR_PROMPT',
    'MODERATOR_PROMPT',
    'REVIEW_BOARD_PROMPT',
    'SECURITY_RESEARCHER_PROMPT_LATER',
    'CODE_AUTHOR_PROMPT_LATER',
    'MODERATOR_PROMPT_LATER',
]
