"""Prompt templates for VulTrial agents"""

from .agent_prompts import (
    # Analysis mode constants
    ANALYSIS_MODE_DETAILED,
    ANALYSIS_MODE_CONSENSUS,
    # Detailed mode prompts (original)
    SECURITY_RESEARCHER_PROMPT,
    CODE_AUTHOR_PROMPT,
    MODERATOR_PROMPT,
    REVIEW_BOARD_PROMPT,
    SECURITY_RESEARCHER_ASSISTANT_PROMPT,
    CODE_AUTHOR_ASSISTANT_PROMPT,
    # Detailed mode - later turns
    SECURITY_RESEARCHER_PROMPT_LATER,
    CODE_AUTHOR_PROMPT_LATER,
    MODERATOR_PROMPT_LATER,
    # Consensus mode prompts (new)
    SECURITY_RESEARCHER_PROMPT_CONSENSUS,
    CODE_AUTHOR_PROMPT_CONSENSUS,
    SECURITY_RESEARCHER_PROMPT_CONSENSUS_LATER,
    CODE_AUTHOR_PROMPT_CONSENSUS_LATER,
    MODERATOR_PROMPT_CONSENSUS,
    REVIEW_BOARD_PROMPT_CONSENSUS,
    SECURITY_RESEARCHER_ASSISTANT_PROMPT_CONSENSUS,
    CODE_AUTHOR_ASSISTANT_PROMPT_CONSENSUS,
    # Utility prompts
    CONTEXT_SUMMARIZER_PROMPT,
    FILE_SUMMARY_PROMPT,
    FUNCTION_SUMMARY_PROMPT,
    README_SUMMARY_PROMPT,
    # Assessment prompts
    FILE_ASSESSMENT_PROMPT,
    CODEBASE_ASSESSMENT_PROMPT,
)

__all__ = [
    # Analysis modes
    'ANALYSIS_MODE_DETAILED',
    'ANALYSIS_MODE_CONSENSUS',
    # Detailed mode prompts
    'SECURITY_RESEARCHER_PROMPT',
    'CODE_AUTHOR_PROMPT',
    'MODERATOR_PROMPT',
    'REVIEW_BOARD_PROMPT',
    'SECURITY_RESEARCHER_ASSISTANT_PROMPT',
    'CODE_AUTHOR_ASSISTANT_PROMPT',
    # Detailed mode - later turns
    'SECURITY_RESEARCHER_PROMPT_LATER',
    'CODE_AUTHOR_PROMPT_LATER',
    'MODERATOR_PROMPT_LATER',
    # Consensus mode prompts
    'SECURITY_RESEARCHER_PROMPT_CONSENSUS',
    'CODE_AUTHOR_PROMPT_CONSENSUS',
    'SECURITY_RESEARCHER_PROMPT_CONSENSUS_LATER',
    'CODE_AUTHOR_PROMPT_CONSENSUS_LATER',
    'MODERATOR_PROMPT_CONSENSUS',
    'REVIEW_BOARD_PROMPT_CONSENSUS',
    'SECURITY_RESEARCHER_ASSISTANT_PROMPT_CONSENSUS',
    'CODE_AUTHOR_ASSISTANT_PROMPT_CONSENSUS',
    # Utility prompts
    'CONTEXT_SUMMARIZER_PROMPT',
    'FILE_SUMMARY_PROMPT',
    'FUNCTION_SUMMARY_PROMPT',
    'README_SUMMARY_PROMPT',
    # Assessment prompts
    'FILE_ASSESSMENT_PROMPT',
    'CODEBASE_ASSESSMENT_PROMPT',
]
